// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_tLeJ2HmYuLiC9CiotwpRsJMlYb8rMns',
    appId: '1:516394010109:web:bddb31fa9d49a24137c594',
    messagingSenderId: '516394010109',
    projectId: 'flutterfirebase-28c2e',
    authDomain: 'flutterfirebase-28c2e.firebaseapp.com',
    storageBucket: 'flutterfirebase-28c2e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvEJMuzl-UNsb5l5fZswzJSDls4wF4Vzc',
    appId: '1:516394010109:android:ced273e6abd0ba4537c594',
    messagingSenderId: '516394010109',
    projectId: 'flutterfirebase-28c2e',
    storageBucket: 'flutterfirebase-28c2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2Y18C1GvyfGKwsUKjdPwAtjHmEvx7v8',
    appId: '1:516394010109:ios:c8fd3ec870af5dc237c594',
    messagingSenderId: '516394010109',
    projectId: 'flutterfirebase-28c2e',
    storageBucket: 'flutterfirebase-28c2e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG2Y18C1GvyfGKwsUKjdPwAtjHmEvx7v8',
    appId: '1:516394010109:ios:c8fd3ec870af5dc237c594',
    messagingSenderId: '516394010109',
    projectId: 'flutterfirebase-28c2e',
    storageBucket: 'flutterfirebase-28c2e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_tLeJ2HmYuLiC9CiotwpRsJMlYb8rMns',
    appId: '1:516394010109:web:157b2872264bb20b37c594',
    messagingSenderId: '516394010109',
    projectId: 'flutterfirebase-28c2e',
    authDomain: 'flutterfirebase-28c2e.firebaseapp.com',
    storageBucket: 'flutterfirebase-28c2e.firebasestorage.app',
  );
}
